app:
  name: chainlist-parser
  version: 1.0.0

# HTTP Server configuration
server:
  port: 8080

# Logger configuration
logger:
  level: "info" # Log level (debug, info, warn, error, dpanic, panic, fatal)
  encoding: "json" # Log encoding (json or console)

# Chainlist data source
chainlist:
  url: "https://chainid.network/chains.json" # URL to fetch chain data

# RPC Checker configuration
checker:
  check_interval: "15m" # Check every 15 minutes
  check_timeout: "5s"   # Timeout for a single RPC check
  max_workers: 40       # Number of concurrent checker goroutines
  cache_ttl: "30m"      # How long to cache the checked RPC results
  run_on_startup: true  # Check all chains immediately on start?

# Cache configuration
cache:
  default_expiration: "30m"
  cleanup_interval: "1h"