# GitHub Actions workflow for Go project
name: Go Build & Test

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21' # Specify your Go version

    - name: Install Dependencies
      run: go mod tidy

    - name: Build
      run: go build -v ./cmd/api/...

    - name: Test
      run: go test -v ./... 